### PR TITLE
Watch keys

### PR DESCRIPTION
**Pull request by blinkinglight**
#63

### CODE REVIEW

**Comment by HeavyHorst** [comment]
Could you keep the default behaviour if watchKeys is not set so that we don't break existing configs?
A little bit documentation would also be nice :)

LGTM otherwise.

**Comment by HeavyHorst** [comment]
Could you also add the docs here:  https://github.com/HeavyHorst/remco/blob/master/docs/content/config/configuration-options.md#backend-configuration-options next to 
```
prefix(string, optional):
Key path prefix. Default is "".
```

**Comment by blinkinglight** [comment]
ok. thanks, and dont forget to regenerate and upload new docs ;)

**Comment by HeavyHorst** [comment]
Sure :) I always generate the docs when i create a new release.

**Pull request merged**
