### PR TITLE
parse json values

### PR DESCRIPTION
**Pull request by blinkinglight**

### CODE REVIEW

**Comment by blinkinglight** [comment]
use case
```
{% for value in getvs("/cache1/domains/*") %}
{% set data = json(value) %}
{{ data.type }} {{ data.name }} {{ data.addr }}
{% endfor %}
```

**Comment by HeavyHorst** [comment]
Isn't that the same as  this?

```
{% for value in getvs("/cache1/domains/*") %}
{% set data = value | parseYAML %}
{{ data.type }} {{ data.name }} {{ data.addr }}
{% endfor %}
```

**Comment by blinkinglight** [comment]
ok. that works too. its alitle bit confusing. i think documentation needs improvements and more examples.

**Comment by HeavyHorst** [comment]
I totally agree!
I am always happy about pull requests :)

**Comment by blinkinglight** [comment]
ok will check what i can inprove in docs :)

**Pull request closed without merging**
