### PR TITLE
add new method "SortedSet()" to template set object

### PR DESCRIPTION
**Pull request by sseide**
Your implementation adds the very helpful `createMap()` and `createSet()` methods.
As booth objects are backed by a hashmap the order of the items is not defined. Therefore using a set 
to collect all items and write them into the file afterwards produces different files on every run - the checksum
differs every time and the file gets overwritten on every run. This comes a bit of a surprise as "Append" suggests an order.

To get a stable output the new function `SortedSet()` for the Set interface is addded.

Example (added to documentation too):
```
{% set s = createSet() %}
{% s.Append("Moin") %}
{% s.Append("Hi") %}
{% s.Append("Hallo") %}

{% for greeting in s %}
{{ geeting }}
{% endfor %}

{% for greeting in s.SortedSet() %}
{{ geeting }}
{% endfor %}
```
The first run (as possible without this PR only) creates a different file on every run overwriting the old one.
With this new method it is possible to generated predictable output that does not differ between multpile runs of remco.

### CODE REVIEW

**Comment by HeavyHorst** [comment]
Thank you!

**Comment by HeavyHorst** [comment]
```go
func (s interfaceSet) MarshalYAML() (interface{}, error) {
	return s.toSet(), nil
}
func (s interfaceSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.toSet())
}
```

we should probably use the stable output here as well.

**Comment by sseide** [comment]
yes - would help for yaml/json too, missed that.

As the `toSet()` method seems not be usable from inside the template file (get nil as return using it inside a template) i wonder wether this method is needed than or can be deleted / completely replaced with the new public method. I do not know if GO is using it internally anywhere implicitly.

**Comment by HeavyHorst** [comment]
Youre right, the toSet method is only used for json/yaml encoding and can be replaced with the new public method.

**Pull request merged**
